---
- name: installing and launching Metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: download Metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: install Metricbeat deb
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: drop in
    copy:
      src: /etc/ansible/files/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module
    command: metricbeat modules enable docker

  - name: setup metricbeat
    command: metricbeat setup metricbeat

  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
